-- =============================================================
-- Invoxa — database schema
-- No seed data: the first admin account is created via the app's
-- signup screen.
-- =============================================================

CREATE TABLE IF NOT EXISTS `enxure_users` (
  `id`            INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username`      VARCHAR(255) NOT NULL UNIQUE,
  `email`         VARCHAR(255) DEFAULT NULL COMMENT 'The first (id ASC) account''s email must match the email a license was issued to — see lib/license.php',
  `role`          ENUM('admin','member') NOT NULL DEFAULT 'admin' COMMENT 'member = day-to-day invoicing/clients/expenses only, no Settings (besides their own Account tab) or Data Management — see Settings > Users',
  `password_hash` VARCHAR(255) NOT NULL,
  `totp_secret`         VARCHAR(64) DEFAULT NULL COMMENT 'Base32 TOTP secret. NULL = two-factor disabled.',
  `totp_secret_pending` VARCHAR(64) DEFAULT NULL COMMENT 'Generated by totp_setup_init, moved to totp_secret once totp_setup_confirm verifies a code against it.',
  `failed_login_attempts` INT NOT NULL DEFAULT 0 COMMENT 'Wrong password or wrong TOTP/backup code both count — reset to 0 on a fully successful login.',
  `locked_until`   DATETIME DEFAULT NULL COMMENT 'Login (both password and 2FA stages) is refused until this time once failed_login_attempts hits the lockout threshold.',
  `reset_token_hash`    VARCHAR(64) DEFAULT NULL,
  `reset_token_expires` DATETIME DEFAULT NULL,
  `email_verified_at`   DATETIME DEFAULT NULL,
  `verify_token_hash`   VARCHAR(64) DEFAULT NULL,
  `verify_token_expires` DATETIME DEFAULT NULL,
  `created_at`    DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_totp_backup_codes` (
  `id`          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id`     INT NOT NULL COMMENT 'FK to enxure_users.id',
  `code_hash`   VARCHAR(255) NOT NULL COMMENT 'password_hash() of the normalized (dash-stripped, uppercased) code — never stored in plaintext, shown to the admin exactly once at generation time.',
  `used_at`     DATETIME DEFAULT NULL COMMENT 'NULL = still valid. Each code is single-use.',
  `created_at`  DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_api_tokens` (
  `id`            INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `label`         VARCHAR(100) NOT NULL COMMENT 'Admin-chosen name, e.g. "Zapier integration" — purely descriptive.',
  `token_hash`    VARCHAR(64) NOT NULL COMMENT 'SHA-256 hex of the raw token. A fast hash (not bcrypt) is deliberate here: the token itself already has ~160 bits of entropy, so unlike a human password or backup code there is no low-entropy guess to slow down — a fast hash instead gives an indexed exact-match lookup on every API request.',
  `token_prefix`  VARCHAR(16) NOT NULL COMMENT 'First several characters of the raw token, plaintext, so the admin can tell tokens apart in the list. On its own it is nowhere near enough to authenticate.',
  `created_at`    DATETIME DEFAULT CURRENT_TIMESTAMP,
  `last_used_at`  DATETIME DEFAULT NULL,
  `expires_at`    DATETIME DEFAULT NULL COMMENT 'NULL = never expires.',
  `revoked_at`    DATETIME DEFAULT NULL,
  UNIQUE KEY `uniq_token_hash` (`token_hash`),
  INDEX `idx_revoked` (`revoked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_settings` (
  `setting_key`   VARCHAR(50) PRIMARY KEY,
  `setting_value` TEXT COMMENT 'TEXT (not VARCHAR(255)) so it can hold longer values like reminder_email_body and license_key'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_stats_layout` (
  `user_id`      INT NOT NULL COMMENT 'FK to enxure_users.id',
  `pane`         VARCHAR(30) NOT NULL COMMENT 'Statistics subnav tab (revenue, forecasting, clients, ...) or dashboard-tidbits/dashboard-charts',
  `layout_json`  TEXT NOT NULL COMMENT 'JSON array of {id, width, col, hidden} in the user''s chosen card order; width/col meaning is pane-specific (Statistics: width 1=half/2=full, col 0/1; dashboard-charts: width is a 6-unit grid span, col unused)',
  `updated_at`   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `pane`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_clients` (
  `id`             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `client_key`     VARCHAR(10)  NOT NULL UNIQUE COMMENT 'Short key e.g. asj, gjm',
  `client_name`    VARCHAR(100) NOT NULL,
  `email`          VARCHAR(255) NOT NULL,
  `phone`          VARCHAR(50)  NOT NULL DEFAULT '',
  `address`        TEXT,
  `account_name`   VARCHAR(255) DEFAULT '',
  `account_number` VARCHAR(50)  DEFAULT '',
  `monthly_rate`   DECIMAL(10,2) DEFAULT 0.00,
  `payment_terms_days` INT NOT NULL DEFAULT 21 COMMENT 'Days from invoice date to due date, e.g. 15/30/45',
  `billing_frequency` ENUM('weekly','monthly','quarterly','annually') NOT NULL DEFAULT 'monthly' COMMENT 'How often run_recurring bills this client',
  `discount_pct`   DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Applied to recurring invoices for this client, 0-100. Defaults to 0 (no discount).',
  `tax_rate`       DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Applied to recurring invoices for this client, 0-100. Defaults to 0 (no tax).',
  `currency`       VARCHAR(3) NOT NULL DEFAULT '' COMMENT 'ISO 4217 code for this client''s invoices, e.g. USD/EUR/GBP. Empty string = use Settings > General''s instance-wide currency.',
  `is_active`      TINYINT(1) DEFAULT 1,
  `is_test`        TINYINT(1) DEFAULT 0 COMMENT '1 = test/dummy client',
  `portal_token`   VARCHAR(64) DEFAULT NULL UNIQUE COMMENT 'Random token granting access to this client''s read-only portal (?portal=<token>). NULL = portal not enabled for this client.',
  `portal_token_expires_at` DATETIME DEFAULT NULL COMMENT 'NULL = never expires. Checked on every portal/pay request; an expired token behaves the same as an invalid one.',
  `crm_notes`      TEXT,
  `created_at`     DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at`     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_invoices` (
  `id`              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `invoice_number`  VARCHAR(20)  NOT NULL UNIQUE,
  `client_key`      VARCHAR(10)  NOT NULL,
  `client_name`     VARCHAR(100) NOT NULL,
  `recipient_email` VARCHAR(255) NOT NULL,
  `invoice_date`    DATETIME,
  `due_date`        DATE,
  `amount`          DECIMAL(10,2) DEFAULT 0.00,
  `currency`        VARCHAR(3) NOT NULL DEFAULT '' COMMENT 'Snapshotted from the client''s currency at creation time — stays fixed even if the client''s currency is changed later. Empty string = the instance-wide currency at the time this row was created.',
  `status`          ENUM('sent','failed','pending','draft','paid','void') DEFAULT 'pending',
  `paid_at`         DATETIME NULL DEFAULT NULL,
  `paid_amount`     DECIMAL(10,2) NULL DEFAULT NULL,
  `html_content`    MEDIUMTEXT   COMMENT 'Full HTML of the invoice',
  `file_path`       VARCHAR(500) COMMENT 'Relative path on the app filesystem',
  `notes`           TEXT,
  `is_quote`        TINYINT(1) NOT NULL DEFAULT 0,
  `quote_expires_at` DATE NULL DEFAULT NULL COMMENT 'Only meaningful when is_quote=1 — how long the quote is valid for, separate from due_date (which becomes the eventual invoice''s payment due date once converted)',
  `created_at`      DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_client_key`   (`client_key`),
  INDEX `idx_invoice_date` (`invoice_date`),
  INDEX `idx_status`       (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_actions` (
  `id`             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `invoice_id`     INT          NULL     COMMENT 'FK to enxure_invoices.id',
  `invoice_number` VARCHAR(20)  DEFAULT '' COMMENT 'Denormalised for display',
  `action_type`    VARCHAR(50)  NOT NULL  COMMENT 'email_sent|email_failed|manual_send|resent|synced|mark_paid|note_added|viewed',
  `notes`          TEXT,
  `performed_at`   DATETIME DEFAULT CURRENT_TIMESTAMP,
  `performed_by_user_id`   INT NULL COMMENT 'FK to enxure_users.id; NULL for system/cron-triggered rows',
  `performed_by_username`  VARCHAR(190) NULL COMMENT 'Denormalised at insert time so the row stays readable after that user is deleted',
  INDEX `idx_invoice_id`  (`invoice_id`),
  INDEX `idx_action_type` (`action_type`),
  INDEX `idx_performed_at`(`performed_at`),
  INDEX `idx_performed_by_user_id`(`performed_by_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_expenses` (
  `id`             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `expense_date`   DATE NOT NULL,
  `vendor`         VARCHAR(150) NOT NULL DEFAULT '',
  `category`       VARCHAR(50)  NOT NULL DEFAULT 'other' COMMENT 'See expenseCategories() in invoxa.php for the whitelist',
  `amount`         DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `description`    TEXT,
  `receipt_path`   VARCHAR(500) DEFAULT NULL COMMENT 'Legacy single-receipt path, superseded by enxure_expense_receipts — kept for old rows, migrated into that table on boot',
  `recurring_expense_id` INT DEFAULT NULL COMMENT 'FK to enxure_recurring_expenses.id when auto-logged by the recurring cron run, NULL for a manually-entered expense',
  `created_at`     DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at`     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_expense_date` (`expense_date`),
  INDEX `idx_category`     (`category`),
  INDEX `idx_recurring_expense_id` (`recurring_expense_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_recurring_expenses` (
  `id`             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `vendor`         VARCHAR(150) NOT NULL DEFAULT '',
  `category`       VARCHAR(50)  NOT NULL DEFAULT 'other' COMMENT 'See expenseCategories() in invoxa.php for the whitelist',
  `amount`         DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `description`    TEXT,
  `frequency`      ENUM('weekly','monthly','quarterly','annually') NOT NULL DEFAULT 'monthly',
  `is_active`      TINYINT(1) NOT NULL DEFAULT 1,
  `created_at`     DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at`     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_expense_receipts` (
  `id`             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `expense_id`     INT NOT NULL COMMENT 'FK to enxure_expenses.id',
  `filename`       VARCHAR(255) NOT NULL COMMENT 'Original uploaded filename, shown in the UI',
  `stored_path`    VARCHAR(500) NOT NULL COMMENT 'Relative path under invoxa-invoices/receipts/<expense_id>/',
  `file_size`      INT NOT NULL DEFAULT 0,
  `doc_type`       ENUM('invoice','receipt') NOT NULL DEFAULT 'receipt' COMMENT 'Which of the Add Expense modal''s two upload slots this came from — receipt OCR only reads doc_type=receipt files',
  `uploaded_at`    DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_expense_id` (`expense_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_payments` (
  `id`             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `invoice_id`     INT NOT NULL COMMENT 'FK to enxure_invoices.id',
  `amount`         DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'This installment only, not a running total — see enxure_invoices.paid_amount for the cached sum',
  `note`           VARCHAR(255) DEFAULT '' COMMENT 'Free-text, e.g. "bank transfer" or "2 of 3"',
  `provider`       VARCHAR(20) NOT NULL DEFAULT 'manual' COMMENT 'manual|stripe|paypal',
  `provider_ref`   VARCHAR(255) DEFAULT NULL COMMENT 'Stripe checkout session id / PayPal capture id — used as an idempotency key so a redelivered webhook or a webhook racing the return-URL handler can never double-credit the same payment',
  `paid_at`        DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created_at`     DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_invoice_id` (`invoice_id`),
  UNIQUE KEY `uniq_provider_ref` (`provider`, `provider_ref`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `enxure_invoice_attachments` (
  `id`             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `invoice_id`     INT NOT NULL COMMENT 'FK to enxure_invoices.id',
  `filename`       VARCHAR(255) NOT NULL COMMENT 'Original uploaded filename, shown in the UI',
  `stored_path`    VARCHAR(500) NOT NULL COMMENT 'Relative path under invoxa-invoices/attachments/<invoice_id>/',
  `file_size`      INT NOT NULL DEFAULT 0,
  `uploaded_at`    DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_invoice_id` (`invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
